tasks:
  - init: |
      pip install --upgrade pip wheel setuptools
      python manage.py migrate
    command: |
      python manage.py runserver
ports: 
  - port: 8000
    visibility: public
    onOpen: open-browse