# Generated by Django 4.1.2 on 2022-10-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='apelido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='bairroAbordagem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='cadUnico',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='cartaoSus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='certNascimento',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='cor',
            field=models.CharField(choices=[('Parda', 'Parda'), ('Amarelo', 'Amarela'), ('Negra', 'Negro/Preta'), ('Branca', 'branca'), ('indigena', 'Indigena')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='naturalidade',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nomeMAe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nomePai',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='rg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='ruaAbordagem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='tempoManaus',
            field=models.CharField(choices=[('1a5', 'Entre 1 a 5 anos'), ('16+', 'Mais de 16 anos'), ('11a15', 'Entre 11 a 15 anos'), ('6a10', 'Entre 6 a 10 anos'), ('-1', 'Menos de 1 ano')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
