# Generated by Django 4.1.2 on 2022-10-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0002_morador_apelido_morador_bairroabordagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='certNascimento',
        ),
        migrations.AddField(
            model_name='morador',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='apelido',
            field=models.CharField(max_length=30, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='bairroAbordagem',
            field=models.CharField(max_length=50, null=True, verbose_name='Bairro Abordagem'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cadUnico',
            field=models.CharField(max_length=30, null=True, verbose_name='Cad. Único'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cartaoSus',
            field=models.CharField(max_length=30, null=True, verbose_name='Cartão SUS'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cor',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Amarelo', 'Amarela'), ('indigena', 'Indigena'), ('Negra', 'Negro/Preta'), ('Parda', 'Parda')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='naturalidade',
            field=models.CharField(max_length=25, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nomeMAe',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nomePai',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='rg',
            field=models.CharField(max_length=30, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='ruaAbordagem',
            field=models.CharField(max_length=50, null=True, verbose_name='Rua Abordagem'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tempoManaus',
            field=models.CharField(choices=[('11a15', 'Entre 11 a 15 anos'), ('1a5', 'Entre 1 a 5 anos'), ('-1', 'Menos de 1 ano'), ('6a10', 'Entre 6 a 10 anos'), ('16+', 'Mais de 16 anos')], max_length=20, null=True, verbose_name='Tempo em Manaus'),
        ),
    ]
