# Generated by Django 4.1.2 on 2022-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0004_alter_morador_cor_alter_morador_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='morador',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cor',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Negra', 'Negro/Preta'), ('indigena', 'Indigena'), ('Amarelo', 'Amarela'), ('Parda', 'Parda')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tempoManaus',
            field=models.CharField(choices=[('11a15', 'Entre 11 a 15 anos'), ('-1', 'Menos de 1 ano'), ('16+', 'Mais de 16 anos'), ('1a5', 'Entre 1 a 5 anos'), ('6a10', 'Entre 6 a 10 anos')], max_length=20, null=True, verbose_name='Tempo em Manaus'),
        ),
    ]
