# Generated by Django 4.1.2 on 2022-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0005_remove_morador_date_joined_morador_datacadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='idade',
        ),
        migrations.AddField(
            model_name='morador',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cor',
            field=models.CharField(choices=[('Branca', 'Branca'), ('Parda', 'Parda'), ('Amarelo', 'Amarela'), ('indigena', 'Indigena'), ('Negra', 'Negro/Preta')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='dataCadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tempoManaus',
            field=models.CharField(choices=[('11a15', 'Entre 11 a 15 anos'), ('-1', 'Menos de 1 ano'), ('6a10', 'Entre 6 a 10 anos'), ('16+', 'Mais de 16 anos'), ('1a5', 'Entre 1 a 5 anos')], max_length=20, null=True, verbose_name='Tempo em Manaus'),
        ),
    ]
