# Generated by Django 4.1.2 on 2022-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0006_remove_morador_idade_morador_datanascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='dataCadastro',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='dataNascimento',
        ),
        migrations.AddField(
            model_name='morador',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='morador',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração'),
        ),
        migrations.AddField(
            model_name='morador',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='cor',
            field=models.CharField(choices=[('Parda', 'Parda'), ('Branca', 'Branca'), ('Amarelo', 'Amarela'), ('indigena', 'Indigena'), ('Negra', 'Negro/Preta')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='tempoManaus',
            field=models.CharField(choices=[('11a15', 'Entre 11 a 15 anos'), ('-1', 'Menos de 1 ano'), ('1a5', 'Entre 1 a 5 anos'), ('16+', 'Mais de 16 anos'), ('6a10', 'Entre 6 a 10 anos')], max_length=20, null=True, verbose_name='Tempo em Manaus'),
        ),
    ]
